name: variety
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rflutter_alert: ^1.0.3
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  audioplayers: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/note1.wav
    - assets/note2.wav
    - assets/note3.wav
    - assets/note4.wav
    - assets/note5.wav
    - assets/note6.wav
    - assets/note7.wav
    - images/

  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: SourceSansPro-Regular
    fonts:
      - asset: fonts/SourceSansPro-Regular.ttf











